### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.dottedname#4]
This package is not yet compatible with Python 3.6, see https://travis-ci.org/zopefoundation/zopetoolkit/jobs/173487024#L787

**Comment by mgedmin** [comment]
Here's the failure log:
```
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
Failure in test /home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/README.txt
Failed doctest test for README.txt
  File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/README.txt", line 0
----------------------------------------------------------------------
File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/README.txt", line 25, in README.txt
Failed example:
    resolve('non existent module')
Differences (ndiff with -expected +actual):
      Traceback (most recent call last):
    - ...
    +   File "/opt/python/3.6-dev/lib/python3.6/doctest.py", line 1330, in __run
    +     compileflags, 1), test.globs)
    +   File "<doctest README.txt[4]>", line 1, in <module>
    +     resolve('non existent module')
    +   File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/resolve.py", line 30, in resolve
    +     found = __import__(used)
    - ImportError: No module named non existent module
    ? ^^^ ^
    + ModuleNotFoundError: No module named 'non existent module'
    ? ^ ^^^^^^ +++++                       +                   +
----------------------------------------------------------------------
File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/README.txt", line 30, in README.txt
Failed example:
    resolve('__doc__')
Differences (ndiff with -expected +actual):
      Traceback (most recent call last):
    - ...
    +   File "/opt/python/3.6-dev/lib/python3.6/doctest.py", line 1330, in __run
    +     compileflags, 1), test.globs)
    +   File "<doctest README.txt[5]>", line 1, in <module>
    +     resolve('__doc__')
    +   File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/resolve.py", line 30, in resolve
    +     found = __import__(used)
    - ImportError: No module named __doc__
    ? ^^^ ^
    + ModuleNotFoundError: No module named '__doc__'
    ? ^ ^^^^^^ +++++                       +       +
----------------------------------------------------------------------
File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/README.txt", line 35, in README.txt
Failed example:
    resolve('logging.foo')
Differences (ndiff with -expected +actual):
      Traceback (most recent call last):
    - ...
    - ImportError: No module named ...foo
    +   File "/opt/python/3.6-dev/lib/python3.6/doctest.py", line 1330, in __run
    +     compileflags, 1), test.globs)
    +   File "<doctest README.txt[6]>", line 1, in <module>
    +     resolve('logging.foo')
    +   File "/home/travis/build/zopefoundation/zopetoolkit/eggs/zope.dottedname-4.1.0-py3.6.egg/zope/dottedname/resolve.py", line 36, in resolve
    +     __import__(used)
    + ModuleNotFoundError: No module named 'logging.foo'
  Ran 1 tests with 1 failures, 0 errors and 0 skipped in 0.008 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
```

Should be simple to fix with a doctest renormalizer.

**Comment by mgedmin** [comment]
Note that I cannot reproduce this with `tox -e py36`, which leads me to a horrible suspicion that `python setup.py test` skips parts of the test suite.

**Comment by mgedmin** [comment]
Turns out I cannot reproduce this with `bin/test` either.  What's going on?

**Comment by mgedmin** [comment]
AFAICT the docstrings embedded in the Sphinx documentation are not part of zope.dottedname's test suite.  Should they be?

**Comment by tseaver** [comment]
> AFAICT the docstrings embedded in the Sphinx documentation are not part of zope.dottedname's test suite. Should they be?

`zope.dottedname` has 100% test coverage and passes them all on Python 3.6.  I'm opposed to treating doctest failures as "gating" precisely because they are flaky against changes in new Python releases.  I consider the whole renormalizer dance to be a nightmare.

Note that test failure is in tests run for the `zopetoolkit` package, which is overzealously tickling the docstrings somehow.
